const alunos = ['Luiz', 'Maria', 'Pedro'];
console.log('Alunos:',alunos);
console.log('aluno[0]:', alunos[0]);
console.log('alunos[alunos.length -1]: ', alunos[alunos.length -1]);
alunos[2] = 'Francisco';
alunos.push('Luiza');
console.log('- Adicionando um elemento no final: alunos.push("Luiza")');
console.log('Alunos: ',alunos);
alunos.unshift('Débora');
console.log('- Adicionando um elemento no início: alunos.unshift("Débora")');
console.log('Alunos: ',alunos);
alunos.pop();
console.log('- Removendo último elemento do array: alunos.pop() ');
console.log('Alunos: ',alunos);
let removido = alunos.pop();
console.log('- Removendo o último elemento e salvando e uma variável: removido = alunos.pop()');
console.log('Removido: ',removido);
console.log('Alunos: ',alunos);
removido = alunos.shift();
console.log('- Removendo o primeiro elemento do array: alunos.shift()');
console.log('Removido: ', removido);
console.log('Alunos: ',alunos);
console.log('- Almentando o array: alunos.push("Fernanda")...');
alunos.push('Fernanda');
alunos.push('Grabriel');
alunos.push('Eduarda');
console.log('Alunos: ',alunos);
console.log('- Removendo um elemento no array mas mantendo o indice: delele alunos[2]');
delete alunos[2];
console.log('Alunos: ',alunos);
console.log('- Adicionando aluno na posição 2: alunos[2]="Sivia"');
alunos[2]="Silvia";
console.log('Alunos: ',alunos);
console.log("- Fatiando o array: alunos.slice(0, 3)");
console.log('Array fatiado: ',alunos.slice(0,3));
console.log('- Criando um novo array fatiando o anterior');
let newAlunos = alunos.slice(0, 3);
console.log('Novo array: ', newAlunos);
console.log('Alunos: ',alunos);
console.log('- Fatiando o array retirando o último elemento: alunos.slice(0, -1)');
console.log('Alunos fatiado: ', alunos.slice(0,-1));
console.log('Verificando se é um array: alunos instanceof array');
console.log('Alunos é um array ?: ', alunos instanceof Array);